version: '3.4'

services:
  clamav-server:
    image: mkodockx/docker-clamav  
    networks:
      - clamav
  restav:
    image: ${DOCKER_REGISTRY-}restav
    build:
      context: .
      dockerfile: RestAV/Dockerfile
    ports:
      - "443:443"
      - "4080:80"
    networks:
      - clamav
networks:
   clamav: